services:
  - type: web
    name: chunav-mitra-frontend
    runtime: node
    rootDir: chunav-shadi-assistant-main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: VITE_API_BASE_URL
        value: https://chunav-mitra-av4k.onrender.com
      - key: NODE_VERSION
        value: 22.12.0
      - key: NODE_ENV
        value: production
