/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoterCheckRouteImport } from './routes/voter-check'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BoothRouteImport } from './routes/booth'
import { Route as IndexRouteImport } from './routes/index'

const VoterCheckRoute = VoterCheckRouteImport.update({
  id: '/voter-check',
  path: '/voter-check',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothRoute = BoothRouteImport.update({
  id: '/booth',
  path: '/booth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booth': typeof BoothRoute
  '/chat': typeof ChatRoute
  '/dictionary': typeof DictionaryRoute
  '/timeline': typeof TimelineRoute
  '/voter-check': typeof VoterCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booth': typeof BoothRoute
  '/chat': typeof ChatRoute
  '/dictionary': typeof DictionaryRoute
  '/timeline': typeof TimelineRoute
  '/voter-check': typeof VoterCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booth': typeof BoothRoute
  '/chat': typeof ChatRoute
  '/dictionary': typeof DictionaryRoute
  '/timeline': typeof TimelineRoute
  '/voter-check': typeof VoterCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booth'
    | '/chat'
    | '/dictionary'
    | '/timeline'
    | '/voter-check'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/booth' | '/chat' | '/dictionary' | '/timeline' | '/voter-check'
  id:
    | '__root__'
    | '/'
    | '/booth'
    | '/chat'
    | '/dictionary'
    | '/timeline'
    | '/voter-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoothRoute: typeof BoothRoute
  ChatRoute: typeof ChatRoute
  DictionaryRoute: typeof DictionaryRoute
  TimelineRoute: typeof TimelineRoute
  VoterCheckRoute: typeof VoterCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voter-check': {
      id: '/voter-check'
      path: '/voter-check'
      fullPath: '/voter-check'
      preLoaderRoute: typeof VoterCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth': {
      id: '/booth'
      path: '/booth'
      fullPath: '/booth'
      preLoaderRoute: typeof BoothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoothRoute: BoothRoute,
  ChatRoute: ChatRoute,
  DictionaryRoute: DictionaryRoute,
  TimelineRoute: TimelineRoute,
  VoterCheckRoute: VoterCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
